### ISSUE TITLE
Some error down in passing data to lingpy

### ISSUE THREAD

**Issue by Anaphory** [Anaphory/simuling#9]
On the with_tests branch:

```
Traceback (most recent call last):
  File "/usr/lib64/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib64/python3.5/cProfile.py", line 160, in <module>
    main()
  File "/usr/lib64/python3.5/cProfile.py", line 153, in main
    runctx(code, globs, None, options.outfile, options.sort)
  File "/usr/lib64/python3.5/cProfile.py", line 20, in runctx
    filename, sort)
  File "/usr/lib64/python3.5/profile.py", line 64, in runctx
    prof.runctx(statement, globals, locals)
  File "/usr/lib64/python3.5/cProfile.py", line 100, in runctx
    exec(cmd, globals, locals)
  File "/home/gereon/sideprojects/simuling/simulingvirtualenv/bin/phylo", line 11, in <module>
    load_entry_point('simuling', 'console_scripts', 'phylo')()
  File "/home/gereon/sideprojects/simuling/phylo/cli.py", line 87, in main
    change_range=cmax, change_min=cmin, basic_list=basic)
  File "/home/gereon/sideprojects/simuling/phylo/cli.py", line 31, in run
    wl.calculate('diversity', ref='cog2id')
  File "/home/gereon/sideprojects/simuling/simulingvirtualenv/lib/python3.5/site-packages/lingpy/basic/wordlist.py", line 557, in calculate
    calculate_data(self, data, taxa, concepts, ref, **keywords)
  File "/home/gereon/sideprojects/simuling/simulingvirtualenv/lib/python3.5/site-packages/lingpy/basic/ops.py", line 229, in calculate_data
    (len(etd) - wordlist.height) / (len(wordlist) - wordlist.height)
ZeroDivisionError: division by zero
```

**Comment by Anaphory** [comment]
`with_tests` is obsolete.
